repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.4
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
      - id: check-dependabot

  - repo: local
    hooks:
      - id: mojo-format
        name: mojo-format
        entry: mojo format -l 100
        language: system
        files: '\.(mojo|🔥)$'

ci:
  skip:
    - mojo-format
