name: quality-check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-code:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15
    env:
      PLATFORM: ${{ matrix.platform }}
      PYTHONUTF8: 1  # https://peps.python.org/pep-0540/
      COLORTERM: truecolor
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.6
      - name: Install Python
        uses: actions/setup-python@v5.1.0
      - name: Install Just
        uses: extractions/setup-just@v2
      - name: Install Mojo
        run: |
          curl https://get.modular.com | sh -
          modular auth examples
          modular install mojo
          echo "/home/runner/.modular/pkg/packages.modular.com_mojo/bin/" >> $GITHUB_PATH
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
      - name: Run tests
        run: just test
