name: quality-check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-code:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15
    env:
      PLATFORM: ${{ matrix.platform }}
      PYTHONUTF8: 1  # https://peps.python.org/pep-0540/
      COLORTERM: truecolor
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.2
      - name: Install Python
        uses: actions/setup-python@v5
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: mojo-format
      - name: Install Just
        uses: extractions/setup-just@v2
#      - name: Install Mojo
#        run: |
#          curl https://get.modular.com | MODULAR_AUTH=${{ secrets.MODULAR_AUTH }} sh -
#          modular auth ${{ secrets.MODULAR_AUTH }}
#          modular install mojo
#      - name: Run tests
#        run: just test
